runtime: python39

entrypoint: gunicorn -b :$PORT repair_shop_finder.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: 'repair_shop_finder.settings'
  SECRET_KEY: 'django-insecure-412f3j+3_&+n1qlk9h$y7u4i9u4ex#%2@b@z&h!b5e&(p2h%'

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto
